### PR TITLE
Add support for music database format v74

### LINKED ISSUE #281: Kodi 19 Music database format changed
Music database format is changed and no longer compatible.

**Logs**
```
2020-04-19 12:38:23.072 T:15094    INFO <general>: JELLYFIN.library -> INFO::jellyfin_kodi/library.py:245 -->[ q:updated/MusicAlbum/139732332153544 ]
2020-04-19 12:38:23.079 T:15141    INFO <general>: JELLYFIN.database -> DEBUG::jellyfin_kodi/database/__init__.py:58 --->[ database: music ] 139732064713392
2020-04-19 12:38:23.085 T:15141    INFO <general>: JELLYFIN.database -> DEBUG::jellyfin_kodi/database/__init__.py:58 --->[ database: jellyfin ] 139732064713616
2020-04-19 12:38:23.098 T:15141    INFO <general>: JELLYFIN.objects.music -> DEBUG::jellyfin_kodi/objects/music.py:164 UPDATE album [26] Albumname: hexid
2020-04-19 12:38:23.105 T:15141    INFO <general>: JELLYFIN.library -> ERROR::jellyfin_kodi/library.py:632 no such column: iYear
                                                   Traceback (most recent call last):
                                                     File "jellyfin_kodi/library.py", line 626, in run
                                                       if obj(item) and self.notify:
                                                     File "jellyfin_kodi/helper/wrapper.py", line 103, in wrapper
                                                       return func(*args, **kwargs)
                                                     File "jellyfin_kodi/helper/wrapper.py", line 117, in wrapper
                                                       return func(self, item, e_item=e_item, *args, **kwargs)
                                                     File "jellyfin_kodi/objects/music.py", line 146, in album
                                                       self.update_album(*values(obj, QU.update_album_obj))
                                                     File "jellyfin_kodi/objects/kodi/music.py", line 164, in update_album
                                                       self.cursor.execute(QU.update_album72, args)
                                                   sqlite3.OperationalError: no such column: iYear
```

**System:**
 - Kodi Version: 19 nightlies
 - Addon Version: master

### PR DESCRIPTION
**Pull request by z3ntu**
See the following commit for reference:
  https://github.com/xbmc/xbmc/commit/8fb8a640e076aa6fdd0c554892630d97bb067d07

Fixes #281

With these changes I could import my music library into Kodi (version: commit c6d47fe20b1)
image

The changes are essentially s/iYear/strReleaseDate/g

### CODE REVIEW

**Comment by z3ntu** [comment]
Actually I can't seem to play any music from the library then:
```
2020-06-17 20:31:01.554 T:202971   DEBUG <general>: CGUIMediaWindow::GetDirectory (musicdb://albums/19/)
2020-06-17 20:31:01.554 T:202971   DEBUG <general>:   ParentPath = [musicdb://albums/]
2020-06-17 20:31:01.554 T:210924   DEBUG <general>: Thread waiting start, auto delete: false
2020-06-17 20:31:01.560 T:210924   DEBUG <general>: GetSongsFullByWhere query = SELECT songview.*, songartistview.* FROM songview JOIN songartistview ON songartistview.idSong = songview.idSong WHERE songview.idAlbum = 19 ORDER BY songview.idSong, songartistview.idRole, songartistview.iOrder
2020-06-17 20:31:01.562 T:210924   ERROR <general>: GetSongsFullByWhere: out of memory loading query: 
2020-06-17 20:31:01.564 T:210924   ERROR <general>: GetDirectory - Error getting musicdb://albums/19/
2020-06-17 20:31:01.564 T:210924   DEBUG <general>: Thread waiting 140676981675776 terminating
2020-06-17 20:31:01.564 T:202971   ERROR <general>: CGUIMediaWindow::GetDirectory(musicdb://albums/19/) failed
2020-06-17 20:31:01.564 T:202971   DEBUG <general>: CGUIMediaWindow::GetDirectory (musicdb://albums/)
2020-06-17 20:31:01.564 T:202971   DEBUG <general>:   ParentPath = []
2020-06-17 20:31:01.564 T:210925   DEBUG <general>: Thread waiting start, auto delete: false
2020-06-17 20:31:01.566 T:210925   DEBUG <general>: GetAlbumsByWhere query: SELECT albumview.* FROM albumview  WHERE albumview.strReleaseType = 'album' ORDER BY albumview.idAlbum
2020-06-17 20:31:01.571 T:210925   DEBUG <general>: GetAlbumsByWhere: Time to fill list with albums 5ms query took 3ms
```
The query printed there can be run fine directly on the MyMusic77.db database (`sqlite3 ~/.kodi/userdata/Database/MyMusic77.db 'SELECT songview.*, songartistview.* FROM songview JOIN songartistview ON songartistview.idSong = songview.idSong WHERE songview.idAlbum = 19 ORDER BY songview.idSong, songartistview.idRole, songartistview.iOrder'`) so I'm not really sure what this is. The error is from here: https://github.com/xbmc/xbmc/blob/master/xbmc/music/MusicDatabase.cpp#L5411 but it seems to be a rather general try-catch so I wouldn't be surprised if it's not "out of memory" (I have 16GB of RAM and only ~8.5GB are used)

**Comment by oddstr13** [comment]
This is the block throwing the error, no idea of what's actually going wrong in there however....

https://github.com/xbmc/xbmc/blob/075fe4e41c9a1e3c7babd59276cc666001b4b209/xbmc/music/MusicDatabase.cpp#L5614L5649

**Comment by z3ntu** [comment]
Figured out what's wrong (kind of) :tada: 
image
```diff
diff --git a/xbmc/music/MusicDatabase.cpp b/xbmc/music/MusicDatabase.cpp
index 3639722ee8e..af8b35e375e 100644
--- a/xbmc/music/MusicDatabase.cpp
+++ b/xbmc/music/MusicDatabase.cpp
@@ -2744,8 +2744,8 @@ CSong CMusicDatabase::GetSongFromDataset(const dbiplus::sql_record* const record
   song.dateAdded.SetFromDBDateTime(record->at(offset + song_dateAdded).get_asString());
   song.dateNew.SetFromDBDateTime(record->at(offset + song_dateNew).get_asString());
   song.dateUpdated.SetFromDBDateTime(record->at(offset + song_dateModified).get_asString());
-  song.iStartOffset = record->at(offset + song_iStartOffset).get_asInt();
-  song.iEndOffset = record->at(offset + song_iEndOffset).get_asInt();
+  song.iStartOffset = 0; // FIXME record->at(offset + song_iStartOffset).get_asInt();
+  song.iEndOffset = 0; // FIXME record->at(offset + song_iEndOffset).get_asInt();
   song.strMusicBrainzTrackID = record->at(offset + song_strMusicBrainzTrackID).get_asString();
   song.rating = record->at(offset + song_rating).get_asFloat();
   song.userrating = record->at(offset + song_userrating).get_asInt();
@@ -2789,9 +2789,9 @@ void CMusicDatabase::GetFileItemFromDataset(const dbiplus::sql_record* const rec
   item->GetMusicInfoTag()->SetTitle(record->at(song_strTitle).get_asString());
   item->GetMusicInfoTag()->SetDiscSubtitle(record->at(song_strDiscSubtitle).get_asString());
   item->SetLabel(record->at(song_strTitle).get_asString());
-  item->m_lStartOffset = record->at(song_iStartOffset).get_asInt64();
+  item->m_lStartOffset = 0; // FIXME record->at(song_iStartOffset).get_asInt64(); // FIXME returns ->at() returns empty string
   item->SetProperty("item_start", item->m_lStartOffset);
-  item->m_lEndOffset = record->at(song_iEndOffset).get_asInt64();
+  item->m_lEndOffset = 0; // FIXME record->at(song_iEndOffset).get_asInt64();
   item->GetMusicInfoTag()->SetMusicBrainzTrackID(record->at(song_strMusicBrainzTrackID).get_asString());
   item->GetMusicInfoTag()->SetRating(record->at(song_rating).get_asFloat());
   item->GetMusicInfoTag()->SetUserrating(record->at(song_userrating).get_asInt());
```
Not sure if both of those hunks are needed or just one. Basically the `iStartOffset` and `iEndOffset` values are `null` in the database which becomes an empty string (`""`) making the conversion to an integer crash in `field_value::get_asInt64`. Not sure if we have to put 0 values into the db from the plugin or if it should be fixed on the kodi side (I believe that the Kodi side is broken because the database field is marked as nullable but has no `default` value so `null` values will be inserted which will be unsuccessfully interpreted as integers)

**Comment by z3ntu** [comment]
:tada: https://github.com/xbmc/xbmc/pull/18158 :tada:

**Comment by z3ntu** [comment]
Music playback works fine now with latest kodi 19 from git master

**Pull request merged**
