### PR TITLE
Add explicit file encoding to file handlers

### PR DESCRIPTION
**Pull request by TrueTechy**
As part of one of the log file in #97 there was exceptions noting the system couldn't determine the default encoding thus they're now coded explicitly

>  ERROR: Exception in thread Thread-18:
>                                             Traceback (most recent call last):
>                                               File "/home/jenkins/workspace/Android-ARM64-Leia/tools/depends/xbmc-depends/aarch64-linux-android-21-release/lib/python2.7/threading.py", line 801, in __bootstrap_inner
>                                               File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.jellyfin/resources/lib/library.py", line 101, in run
>                                                 if not self.startup():
>                                               File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.jellyfin/resources/lib/library.py", line 325, in startup
>                                                 Views().get_views()
>                                               File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.jellyfin/resources/lib/views.py", line 221, in get_views
>                                                 save_sync(self.sync)
>                                               File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.jellyfin/resources/lib/database/__init__.py", line 357, in save_sync
>                                                 with open(os.path.join(path, 'sync.json'), 'w') as outfile:
>                                             IOError: could not determine default encoding

### CODE REVIEW

**Comment by oddstr13** [comment]
`encoding` is a Python 3 specific keyword argument to `open()`.
This will break for Kodi 17 and Kodi 18.

**Comment by TrueTechy** [comment]
> `encoding` is a Python 3 specific keyword argument to `open()`.
> This will break for Kodi 17 and Kodi 18.

We're using the python library IO which works in both 2 and 3. The docs say python 2 has the encoding options in the [docs]( https://docs.python.org/2/library/io.html)

**Comment by oddstr13** [comment]
Ah, that would be why then. I searched the codebase for more instances of open, but those aren't using the io library.

Should those other `open()` calls also use the IO library then, with the `encoding` argument?

**Comment by TrueTechy** [comment]
We only changed the DB file to IO as a solution to support unicode characters in the server name as that was breaking the addon using non-ascii characters in their server name. We could change them over to IO and specify the encoding we just haven't gotten to reviewing those parts of the code yet

**Pull request merged**
