### PR TITLE
fast sync fix jellyfin/jellyfin-kodi#15

### PR DESCRIPTION
**Pull request by jmeacoe**
…Added "Kodi Sync Queue" to plugins searched when attempting to use fast sync which now matches serverside.

### CODE REVIEW

**Comment by jmeacoe** [comment]
Hey dtorner, I added the space, committed and pushed.  Let me know if there is anything else you need me to do, as this is my first time working with git.

**Comment by dtorner** [comment]
Well, I'm just a user with no admin rights like you, I just jumped in because I had the problem that this pull fixes. I hope an admin will review and approve it in case it is OK to be merged...

**Comment by cvium** [comment]
Honestly, I'd rather the plugin name check wasn't there at all. It should show an error if there's no endpoint listening instead.

**Comment by jmeacoe** [comment]
I agree that there are better potential fixes but as it stands this issue is crippling the usability of the Kodi plugin and negating the jellyfin server plugin completely.
I believe this to be a good fix as a stop gap, and a new issue for improvement can be created, which I should be able to look into it a little later this week, but will take more time as I literally just applied the fix suggested in #15.

**Comment by cvium** [comment]
Approving as a stop-gap

**Pull request merged**
