### PR TITLE
Fix subsequent syncs from the addon menu better

### LINKED ISSUE #511: Can't add/update libraries
**Describe the bug**
I have added 2 libraries successfully but now when I want to update them or add a new one, it always ran into an error.

**To Reproduce**
1. Reset Kodi Local Database from Jellyfin addon
2. Reset jellyfin settings when suggested
3. Kodi restarts
4. Connect to Jellyfin Server
5. Select 1+ Libaries
6. Sync is done successfully
7. Open Jellyfin Addon
8. Try to add another Library or to update the ones just added

**Expected behavior**
It should work as expected

**Logs**
https://pastebin.com/SX4VSmfp

**System (please complete the following information):**
 - OS: LibreElec + Docker
 - Jellyfin Version: 10.7.2
 - Kodi Version: 18.9
 - Addon Version: 0.7.2+py2
 - Playback Mode: Default

### PR DESCRIPTION
**Pull request by mcarlton00**
Fixes #511

Also fixes removing music libraries, which appears to have been broken for over 2 years

Edit: the diff is being stupid.  Basically I just added the for loop and indented everything below it one more level

### CODE REVIEW

**Review by TrueTechy — APPROVED** [review]
Looks good to me. Tested on Kodi 19 and adding & removing libraries works as expected both via manage libraries and context menu

**Comment by the-lazy-fox** [comment]
Hello @mcarlton00 
Any idea when it will be released?
Thanks

**Comment by mcarlton00** [comment]
As soon as #518 gets merged we can trigger a release

**Comment by the-lazy-fox** [comment]
Which is now ok. Great!

**Pull request merged**
