### PR TITLE
Remove default connection port

### PR DESCRIPTION
**Pull request by mcarlton00**
Removes default port mapping of 8096 (discussed in matrix)

### CODE REVIEW

**Comment by dkanada** [comment]
Technically the goal is to remove the port field entirey and just use a hostname field for the entire URL instead.

**Comment by mcarlton00** [comment]
so the idea is to just have something like `192.168.1.10:8096` or `jellyfin.example.com:8096`?  That's going to add a bit of confusion once the baseurl stuff lands.  Some users will inevitably be trying `example.com/jellyfin:8096` and wondering why things aren't working properly.  What's the end goal of not having a port field at all?

**Comment by oddstr13** [comment]
Currently I have to explicitly clear the port field in order to add my server which is under a sub-path behind reverse proxy. I'd prefer a URL field pointing to the Jellyfin base path

**Comment by mcarlton00** [comment]
Personally, I'd rather the ability to leave the port field blank and default to 80/443 internally depending on if https is available.  That way there's sane defaults for the majority of users, but if there's a good reason to override it's easy to do so.  I just really don't like mixing URLs/ports in the same field.  It gets messy and especially once we have working subpaths will likely lead to a lot of user confusion

**Comment by oddstr13** [comment]
Well, I think a "copy paste" from the URL you'd use for the web interface would be easiest for the end user.

Non-default port means that the port is part of the URL.

On October 31, 2019 10:05:53 PM UTC, mcarlton00 <notifications@github.com> wrote:
>Personally, I'd rather the ability to leave the port field blank and
>default to 80/443 internally depending on if https is available.  That
>way there's sane defaults for the majority of users, but if there's a
>good reason to override it's easy to do so.  I just really don't like
>mixing URLs/ports in the same field.  It gets messy and especially once
>we have working subpaths will likely lead to a lot of user confusion
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/jellyfin/jellyfin-kodi/pull/128#issuecomment-548588002

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mcarlton00** [comment]
@oddstr13 @dkanada that should take care of it.  Working fine against my servers, but could use testing from somebody else before we merge to verify

**Comment by TrueTechy** [comment]
Tested on desktop. Syncs and plays fine

**Pull request merged**
