### PR TITLE
Make commands python 2/3 compatible

### PR DESCRIPTION
**Pull request by mcarlton00**
Fixes syncing issues mentioned in #206

### CODE REVIEW

**Comment by druscoe** [comment]
I have much more experience in python2 opposed to python3 so this is my time to learn :)
Is xrange and izip no longer supported in python3?

A concern I have looking at this change is 
Do moves.zip and moves.range return iterators or lists?

Thinking in terms of python2 zip and izip
The usage of izip was important here as it allowed the addon to be processing data while the thread pool was still working in the background. izip returns an iterator which can be iterated before the entire sequence is built.
If this was changed to zip then all threads would need to complete for the result to be built into a list. Processing on the data will only occur after all threads have been executed.

The xrange is much less important

**Comment by TrueTechy** [comment]
xrange became range in python3 as it is just much better than the range in python2. Apparently a similar thing happened with zip and izip

https://stackoverflow.com/questions/32659552/importing-izip-from-itertools-module-gives-nameerror-in-python-3-x

**Comment by druscoe** [comment]
Issue #206 
Works fine on my machine :) lol
Sorry for the breakage.

I was under the assumption that python was shipped with kodi and that version was python3.
I am using Kodi 17.6 on my dev machine and Kodi 18.5 on my android box; neither complain about xrange and izip

My question is how can I guarantee that my patches work with all version of Kodi shipping with different versions of python? Creating bugs is just embarrassing :/

**Comment by druscoe** [comment]
> xrange became range in python3 as it is just much better than the range in python2. Apparently a similar thing happened with zip and izip
> 
> https://stackoverflow.com/questions/32659552/importing-izip-from-itertools-module-gives-nameerror-in-python-3-x

Thank you for this info.

A further clarification if you dont mind.
moves is a util library which helps migrate from python2 to python3. So on a python3 platform moves.zip will be an "alias" to python3 zip and hence return an iterator as opposed to a list.

On a python2 platform is zip "aliasing" itertools.izip or builtin.zip?

**Comment by mcarlton00** [comment]
It's not a problem, I just forgot to check the other day and was starting to look at what needed to be wrapped up for our next release and noticed it.  Python 3 in Kodi land is a relatively new development, currently only available on Kodi 19.  Which depending on your system is either an easy download or a manual compilation process.

Python 3 shuffled lots of stuff around.  Mostly for the better, but it does make supporting a codebase on both versions mildly annoying.  That's where the six library comes into play and helps with that greatly, otherwise you do silly things like my first commit on this PR (forgot six existed for a while there).  You can see more details about `six.moves` at [this section](https://six.readthedocs.io/#module-six.moves) of their docs.  Specifically if you scroll down there's a big table with the python 2/python 3 equivalents.  And yes, it's using `itertools.zip` in python 2 (second from the bottom entry in the list)

**Pull request merged**
