### PR TITLE
Bump version for 0.3.5

### PR DESCRIPTION
**Pull request by mcarlton00**

### CODE REVIEW

**Comment by oddstr13** [comment]
I'm having trouble doing a db reset and full sync against 10.4.1 - may or may not be related to the changes since last time I checked out master - more testing needed, as multiple things changed.

**Comment by mcarlton00** [comment]
Is it related to the baseurl change in the server?  I found that I had to do a full reset and redo the server info/user login before data would start flowing again.

**Comment by mcarlton00** [comment]
We'll merge this after #132 lands.  Might as well get that fix in this release as well since it's right on the edge of being ready

**Comment by mcarlton00** [comment]
ew, that got ugly.  closing and opening a new clean one

**Pull request closed without merging**
