### PR TITLE
Correct filepath when entering data to database

### LINKED ISSUE #53: Incorrect TV Show Metadata/File Issue
I have added my TV and Movie libraries to Kodi using this (pretty awesome) addon, but I am having a problem with a few TV shows, not all of them.

Example of the problem:
I navigate in Kodi to a TV show and go to information for an episode. It shows the correct thumbnail and title for the episode, but shows the plot and actors for a movie in my library. When I play the episode, it actually plays the movie (that the metadata was from). As far as I can tell this issue only effects some of my TV shows (Planet Earth, South Park) and does not appear to affect movies. Some shows will also not show any information at all (which is my "default select" action in Kodi making it very frustrating to play these videos). The metadata in Jellyfin web interface is correct. 

My environment:
Kodi - Windows 10 PC, Latest version of Kodi
Jellyfin - Docker container, Latest version
Addon - Latest version installed from Repo
Kodi Sync Queue plugin is installed

I will attempt to get some screenshots demonstrating this strange occurrance. Any help would be appreciated. It does look to be posibly related to this previously unresolved issue: https://github.com/jellyfin/jellyfin-kodi/issues/24#issue-440057406

### PR DESCRIPTION
**Pull request by mcarlton00**
Fixes #53 

Without including the libraryId in the path, it just kept overwriting the top level with whatever library had most recently synced

### CODE REVIEW

**Comment by cvium** [comment]
What about the other library types?

**Comment by mcarlton00** [comment]
As far as I can tell, it's only an issue with the movies and tv shows libraries.  When I was syncing music it had no effect, but I've never tried music videos or mixed content

**Comment by cvium** [comment]
Isn't it better to keep it consistent though?

**Comment by mcarlton00** [comment]
Generally yes.  I was only focusing on movies/shows to address the known issue.  I'm not sure if the other libraries do the same thing or not, I'll need to check on them later after work today/this weekend

**Comment by mcarlton00** [comment]
Music is in it's own database that's formatted different and is fine, and I've updated Music Videos as well just for consistency's sake

**Comment by LittleCannon** [comment]
I've just applied changes to 2 existing installations and everything is OK now.
No more overwritten metadata.
Well done!

**Pull request merged**
