### PR TITLE
Add more transcoding options

### PR DESCRIPTION
**Pull request by Electry**
I made these changes mostly for my personal use, but I'm parking them here in case someone deems them useful, and perhaps could review them and/or help me test them more extensively.

Anyway, this PR adds more transcoding options to the Settings menu, such as preferred transcoding codec for video/audio, manual bitrate options, max audio channels, and few other changes (described in commit messages).

Max. audio bitrate while transcoding/direct streaming seems to be limited by the backend to [384 kbps](https://github.com/jellyfin/jellyfin/blob/master/MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs#L1370), just like max. channels are [limited to 6](https://github.com/jellyfin/jellyfin/blob/master/MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs#L1459). Transcoding to AC3 could benefit from allowing up to 640 kbps, but that needs to be dealt with on the server side first.

### CODE REVIEW

**Comment by mcarlton00** [comment]
Thanks, nice work.  More config options are always good, and transcoding definitely doesn't get a ton of love since we generally direct play everything.  A quick glance through the code and it looks fine, but I'll do some testing and more in depth review later this week.

In the meantime, if anybody wants to help test this you can download the built zip files from [here](https://dev.azure.com/jellyfin-project/jellyfin/_build/results?buildId=14699&view=artifacts&type=publishedArtifacts)

**Comment by mcarlton00** [comment]
Just fyi, you're ready for this to be reviewed, mark it as ready instead of a draft

**Comment by Electry** [comment]
Added option to transcode VC-1 (no hw decode support on RPi3 without the license key).

I will make a separate PR for the "Maximum artwork resolution" option, since it isn't really related to transcoding.

**Review by mcarlton00 — APPROVED** [review]
Everything seems fine to me.  I haven't seen any errors while testing.  Nice work

**Pull request merged**
