### PR TITLE
Re-add dependency add-ons for cleaner paths

### PR DESCRIPTION
**Pull request by cvium**
Don't merge this until the three dependencies are ready.

cc @joshuaboniface

### CODE REVIEW

**Comment by JustAMan** [comment]
@cvium @joshuaboniface please ping this PR when dependencies are up so we can merge it.

**Comment by anthonylavado** [comment]
@cvium @JustAMan What are we waiting on here?

**Comment by cvium** [comment]
We're waiting for @joshuaboniface to fork the `plugin.video.jellyfin.*` deps.

**Comment by joshuaboniface** [comment]
I forgot all about that. I believe we wanted the beta ones correct?

**Comment by joshuaboniface** [comment]
>believe we wanted the beta ones correct? I've got the whole web archive, but where do we need to put them?

@cvium How do we need to proceed here?

**Comment by oddstr13** [comment]
Dependencies are in https://github.com/jellyfin/jellyfin-kodi-plugins, but not yet in the Kodi repo (https://repo.jellyfin.org/releases/client/kodi/).

I am not entirely sure of what exactly this PR or those plugins are fixing, however.

**Comment by oddstr13** [comment]
@cvium What exactly does this PR attempt to solve?
If this separation is beneficial, would it not be better to use "sub-paths" rather than "domains"? So that we chan avoid having those extra dummy dependencies.

**Comment by oddstr13** [comment]
Closing this as there is no progress nor follow-up.
Reopen or just comment if this is still something we would want to do.

**Pull request closed without merging**
