### PR TITLE
Moved setting addon mode to utils

### PR DESCRIPTION
**Pull request by TrueTechy**
It was the only useful function left in setup.py since we've removed the rest of them over time so figured one less file would be better

### CODE REVIEW

**Comment by mcarlton00** [comment]
There's an issue here.  When upgrading from a previous version or master to this version, it asks if you want the addon or native mode again.  It's not a huge deal, but it will be annoying for our users.  Seems like it's not pulling the previous answer correctly so it asks again.

**Comment by TrueTechy** [comment]
See now the way I was reading the flow it looked like it was going to do that everytime. I'll have a look at that upgrade path

**Comment by mcarlton00** [comment]
borked.  Seems to play fine, but throwing lots of these in the logs.  I'm not seeing it on master, so something here seems to have changed it

```
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
 - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <type 'exceptions.TypeError'>
Error Contents: 'NoneType' object is not callable
Traceback (most recent call last):
  File "/home/matt/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/monitor.py", line 255, in onNotification
    self.player.report_playback(data.get('Report', True))
  File "/home/matt/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/player.py", line 360, in report_playback
    item['Server'].jellyfin.session_progress(data)
  File "/home/matt/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/api.py", line 313, in session_progress
    return self.sessions("/Playing/Progress", "POST", json=data)
  File "/home/matt/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/api.py", line 72, in sessions
    return self._post("Sessions%s" % handler, json, params)
  File "/home/matt/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/api.py", line 56, in _post
    return self._http("POST", handler, {'params': params, 'json': json})
  File "/home/matt/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/api.py", line 50, in _http
    return self.client.request(request)
  File "/home/matt/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/http.py", line 164, in request
    response = r.json()
  File "/home/matt/.kodi/addons/script.module.requests/lib/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python2.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
  File "/usr/lib/python2.7/site-packages/simplejson/errors.py", line 41, in __init__
    ValueError.__init__(self, errmsg(msg, doc, pos, end=end))
TypeError: 'NoneType' object is not callable
-->End of Python script error report<--
```

**Comment by mcarlton00** [comment]
Previous errors (and others) only seem to happen when you update.  After you restart kodi it stops throwing them.  No idea what that's about.

**Pull request merged**
